# Generated by Django 3.2.6 on 2021-08-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image/%Y/%m/%d/'),
        ),
    ]
